FROM python:3.9-buster

ENV PYTHONUNBUFFERED=1

RUN apt-get update

WORKDIR /home/work

COPY poetry.lock pyproject.toml ./

RUN pip install poetry

RUN poetry config virtualenvs.create false \
  && poetry install

CMD bash -c "/bin/bash"
# CMD jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888